// Vendored from scout/src/creative-suite/template/validation/concepts.ts.
//
// Source of truth lives in the scout/ tree (Fernando's drop — immutable).
// We duplicate the literal arrays here because the exodus package is shipped
// as its own tree by scripts/publish-release.sh — cross-tree imports to
// scout/ would break at runtime even if they compiled.
//
// If you update the source, mirror the change here. Both files must stay
// in lockstep.

export const AD_TYPES = [
  "before-after",
  "native-news",
  "testimonial",
  "bold",
  "meme",
  "screenshot",
  "hero",
  "holding-sign",
  "handwritten",
  "comment",
  "breaking-news",
  "lofi",
  "comparison",
  "infographic",
  "headline",
  "collage",
  "product-breakdown",
  "scientific",
  "animation",
  "founder-note",
  "carousel",
  "statistics",
  "post-it-notes",
  "happy-avatar",
  "problem-solution",
  "writing-on-body",
  "multi-testimonial",
  "receipt",
  "step-by-step",
  "sale-promotional-offer",
  "cost-of-inaction",
  "ugc",
  "quiz-interactive",
  // gen:new-bots:AD_TYPES — keep in lockstep with concepts.ts (#324)
  "action-figure",
  "at-home-routine",
  "billboard",
  "black-and-white",
  "blurred",
  "choose",
  "cutout",
  "drawing",
  "facetime",
  "marker",
  "notes",
  "photo",
  "quadrant",
  "search",
  "thumbnail",
  "xray",
  "zoom-bubble",
  "advice-cacophony",
  "annotated-testimonial",
  "body-morph",
  "body-portal",
  "bundle-showcase",
  "clay-world",
  "colossus-product",
  "cost-receipt",
  "cultural-icon-dressup",
  "effect-field",
  "fine-art-intervention",
  "flavor-story",
  "giant-tiny",
  "half-face-reveal",
  "hero-vs-villain",
  "horror-illustration",
  "horror-object-interior",
  "illustrated-cutaway",
  "impossible-physics",
  "ingredient-warrior",
  "lifestyle-colorway-array",
  "material-state",
  "mirror-reveal",
  "object-launch",
  "organ-buddy",
  "polaroid-sticky",
  "pop-art-comic",
  "product-as-body",
  "product-as-hero",
  "retro-game-screen",
  "sequential-state-strip",
  "sketch-equation",
  "spotlight-hero",
  "stat-surround-flatlay",
  "stat-surround-hero",
  "street-find",
  "street-poster",
  "stuffed-container",
  "surrogate-character",
  "symbol-swap",
  "symptom-collage",
  "threat-map",
  "tiny-universe",
  "tiny-world",
  "toxic-assemblage",
  "toxic-emanation",
  "trophy-moment",
  "villain-pour",
  "vintage-reframe",
  "whiteboard",
  "zipper-reveal",
  // /gen:new-bots:AD_TYPES
] as const;

export type AdType = (typeof AD_TYPES)[number];

export const AD_TYPE_NAMES: Record<AdType, string> = {
  "before-after": "Before / After",
  "native-news": "Native News",
  testimonial: "Testimonial",
  bold: "Bold Typography",
  meme: "Meme",
  screenshot: "Screenshot",
  hero: "Hero",
  "holding-sign": "Holding Sign",
  handwritten: "Handwritten Note",
  comment: "Comment / Review",
  "breaking-news": "Breaking News",
  lofi: "Lo-Fi",
  comparison: "Comparison",
  infographic: "Infographic",
  headline: "Headline + Image",
  collage: "Curiosity Collage",
  "product-breakdown": "Product Breakdown",
  scientific: "Scientific Study",
  animation: "Animation",
  "founder-note": "Founder Note",
  carousel: "Carousel",
  statistics: "Statistics",
  "post-it-notes": "Post-It Notes",
  "happy-avatar": "Happy Avatar",
  "problem-solution": "Problem-Solution",
  "writing-on-body": "Writing On Body",
  "multi-testimonial": "Multi-Testimonial",
  receipt: "Receipt",
  "step-by-step": "Step by Step",
  "sale-promotional-offer": "Sale / Promotional Offer",
  "cost-of-inaction": "Cost of Inaction",
  ugc: "UGC",
  "quiz-interactive": "Quiz / Interactive Self-Selection",
  // gen:new-bots:AD_TYPE_NAMES — keep in lockstep with concepts.ts (#324)
  "action-figure": "Action Figure",
  "at-home-routine": "At Home Routine",
  billboard: "Billboard",
  "black-and-white": "Black and White",
  blurred: "Blurred",
  choose: "Choose",
  cutout: "Cutout",
  drawing: "Drawing",
  facetime: "FaceTime",
  marker: "Marker",
  notes: "Notes",
  photo: "Photo",
  quadrant: "Quadrant",
  search: "Search",
  thumbnail: "Thumbnail",
  xray: "X-ray",
  "zoom-bubble": "Zoom Bubble",
  "advice-cacophony": "Advice Cacophony",
  "annotated-testimonial": "Highlighted / Annotated Testimonial",
  "body-morph": "Body Morph",
  "body-portal": "Body Portal",
  "bundle-showcase": "Bundle Showcase + Benefit Bar",
  "clay-world": "Clay World",
  "colossus-product": "Colossus Product",
  "cost-receipt": "Cost Receipt",
  "cultural-icon-dressup": "Cultural Icon Dress-Up",
  "effect-field": "Effect Field",
  "fine-art-intervention": "Fine Art Intervention",
  "flavor-story": "Flavor Story / Tastes Like",
  "giant-tiny": "Giant / Tiny",
  "half-face-reveal": "Half-Face Reveal",
  "hero-vs-villain": "Hero vs Villain",
  "horror-illustration": "Horror Illustration",
  "horror-object-interior": "Horror Object Interior",
  "illustrated-cutaway": "Illustrated Cutaway",
  "impossible-physics": "Impossible Physics",
  "ingredient-warrior": "Ingredient Warrior",
  "lifestyle-colorway-array": "Lifestyle Action + Product Colorway Array",
  "material-state": "Material State",
  "mirror-reveal": "Mirror Reveal",
  "object-launch": "Object Launch",
  "organ-buddy": "Organ Buddy",
  "polaroid-sticky": "Polaroid + Sticky",
  "pop-art-comic": "Pop Art / Comic",
  "product-as-body": "Product as Body",
  "product-as-hero": "Product as Hero",
  "retro-game-screen": "Retro Game Screen",
  "sequential-state-strip": "Sequential State Strip",
  "sketch-equation": "Sketch Equation",
  "spotlight-hero": "Spotlight Hero",
  "stat-surround-flatlay": "Stat Surround / Callout Radial (Lifestyle Flatlay)",
  "stat-surround-hero": "Stat Surround / Callout Radial (Product Hero)",
  "street-find": "Street Find",
  "street-poster": "Street Poster",
  "stuffed-container": "Stuffed Container",
  "surrogate-character": "Surrogate Character",
  "symbol-swap": "Symbol Swap",
  "symptom-collage": "Symptom Collage",
  "threat-map": "Threat Map",
  "tiny-universe": "Tiny Universe",
  "tiny-world": "Tiny World",
  "toxic-assemblage": "Toxic Assemblage",
  "toxic-emanation": "Toxic Emanation",
  "trophy-moment": "Trophy Moment",
  "villain-pour": "Villain Pour",
  "vintage-reframe": "Vintage Reframe",
  "whiteboard": "Whiteboard",
  "zipper-reveal": "Zipper Reveal",
  // /gen:new-bots:AD_TYPE_NAMES
};

export const REPTILE_TRIGGERS = [
  "ultra-real",
  "bizarre",
  "voyeur",
  "suffering",
  "gory",
  "sexual",
  "primal-fear",
  "odd-contrast",
  "inside-joke",
  "time-warp",
  "victory-lap",
  "selfie",
  "uncanny-objects",
] as const;
